version: '3.8'

services:
  # ArangoDB
  arangodb:
    image: arangodb:latest
    container_name: graphmanager-arangodb
    environment:
      ARANGO_ROOT_PASSWORD: 20022012
      ARANGO_DB_NAME: graphmanager
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps_data:/var/lib/arangodb3-apps
    networks:
      - graphmanager-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: graphmanager-backend
    environment:
      - NODE_ENV=production
      - ARANGO_URL=http://arangodb:8529
      - ARANGO_DB=graphmanager
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=20022012
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - arangodb
    networks:
      - graphmanager-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: graphmanager-frontend
    environment:
      - VITE_API_URL=http://localhost:3001/api
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - graphmanager-network
    restart: unless-stopped

volumes:
  arangodb_data:
  arangodb_apps_data:

networks:
  graphmanager-network:
    driver: bridge 